### ISSUE TITLE
DNS issues in kubenetes

### ISSUE THREAD

**Issue by Baggypants** [eggheads/eggdrop-docker#14]
The default configuration of loading the dns module causes eggdrop not to be able to resolve the kubenetes service dns entries using coredns, while cli tools in the continainer can resolve them fine.

e.g. the irc server might be behind the service `ircd.default.svc.cluster.local` eggdrop can't resolve it However: 
```
[root@rancher-singlenode ~]# docker exec -it k8s_egg_egg-948695bb6-g99gn_default_573d819c-0ee6-40b5-8410-659b28391c26_4 /usr/bin/getent ahosts ircd.default.svc.cluster.local
10.43.81.219    STREAM ircd.default.svc.cluster.local
10.43.81.219    DGRAM  ircd.default.svc.cluster.local
```
commenting out `loadmodule dns` in the config resolves this issue.

**Comment by vanosg** [comment]
Hi Baggypants! Thanks so much for taking the time to report this. Yes, this indeed an issue and we have a patch upstream that is being tested to fix the DNS module. The issue has to do with the musl libs only paying lipservice to the initialization of DNS functionality. We hope to have it merged in sometime in the next few days. I'll close this once it hits the official docker library.

Please feel free to find us on #eggdrop on FreeNode if you want to chat or discuss anything else on the topic, it's great to get feedback on this implementation!

**Comment by vanosg** [comment]
Hi Baggypants - just wanted to close this out, what specific functionality wasn't working for you? ie, the name resolution of a server in set servers? Also, was this in the 1.8 or develop branch? Thanks

**Comment by Baggypants** [comment]
I'd need to go back and check my notes. I'll get back to you in about a week.
