### ISSUE TITLE
hardcoded servers in the config file

### ISSUE THREAD

**Issue by Baggypants** [eggheads/eggdrop-docker#15]
The config file in the image contains two hardcoded servers.

```
set servers {

  [2001:db8:618:5c0:263::]:6669:password
  ssl.example.net:+6697
}
```

This causes DNS and connection errors in the log. Possible privacy issues if the ip or dns are ever resolvable in the future.

**Comment by vanosg** [comment]
Those lines in the image file are removed during the initial start and replaced with environmental variables provided on the command line, or a user-provided/edited config file is used. The image doesn't start without a user-specified server present.

The config file itself is an upstream item, but I'll bring it up on that side. Thanks
