### ISSUE TITLE
Alpine doesn't have mysqltcl and TclCurl

### ISSUE THREAD

**Issue by jaloji** [eggheads/eggdrop-docker#22]
Alpine doesn't have this packages so if someone else want to use some packages like this you need to edit the Dockerfile yourself and add this:

RUN wget https://github.com/flightaware/tclcurl-fa/archive/refs/heads/master.zip \
  && unzip master.zip \
  && rm master.zip \
  && ( cd tclcurl-fa-master \
  && ./configure \
  && make \
  && make install ) \
  && rm -rf tclcurl-fa-master
  
RUN wget http://www.xdobry.de/mysqltcl/mysqltcl-3.052.tar.gz \
  && tar -zxvf mysqltcl-3.052.tar.gz \
  && rm mysqltcl-3.052.tar.gz \
  && ( cd mysqltcl-3.052 \
  && ./configure \
  && make \
  && make install ) \
  && rm -rf mysqltcl-3.052

and of course you need to move this "&& apk del egg-deps" at the end of all compiling process.

**Comment by vanosg** [comment]
Hi @jaloji , thanks for sharing this tip. We are offering the eggdrop image as a minimal package, consistent with the Docker principles. Modifying the Dockerfile we provide (or creating a new one locally using the eggdrop image as a base, along with your suggestion above) is a great addition. We're also considering creating a "heavy" image tag that has more Tcl packages and other libraries installed by default, so keep an eye out for that.

To the general community, it would be great to hear feedback if this is of interest to others or not, so we can help prioritize it (and requested packages) appropriately. Thanks!
