### ISSUE TITLE
Alpine 3.4 end-of-life 

### ISSUE THREAD

**Issue by vielmetti** [eggheads/eggdrop-docker#8]
> As @bmw pointed out in docker-library/python#265 Alpine 3.4 will reach its end of life on 2018-05-01. Are there plans to deal with this? 

As noted in https://github.com/docker-library/official-images/issues/4275 - the line in question is at https://github.com/eggheads/eggdrop-docker/blob/master/1.6/Dockerfile#L1

**Comment by vanosg** [comment]
Thanks for the heads up, @vielmetti , we'll ween ourselves overt to a newer image shortly. Thanks!

**Comment by vanosg** [comment]
Official library updated, 1.6.21 removed.
